### ISSUE TITLE
Some TODO

### ISSUE THREAD

**Issue by wheeler** [wheeler/connections-game#1]
Functionality
- [x] deploy on github pages
- [x] Implement shuffle
- [ ] Make multiple games or allow creation of games (fetch?)

Improve structure of code
- [x] move initial words into game data
- [x] typescript or proptypes
- [ ] ~separate solved and unsolved board components~
- [ ] restructure win/lose presentation at end of game
- [ ] extract game buttons component

Parity
- [ ] NYT actually keeps tracked of all previous guesses and prevents them from being re-guessed
- [ ] NYT shows a summary of your guesses when you win
- [ ] NYT shows you the correct solution when you lose

Animations
- [ ] correct guess - the selected items animate up into the top row
- [x] correct guess - the remaining items in the top row fill in the gaps left by the correct items
- [ ] wrong guess (shakes head)
- [x] shuffle (theirs just fades out. I might try a full position swap)
